using final_proj.Models;
using Microsoft.EntityFrameworkCore;

namespace final_proj.Setup;

public static class AppSchemaInitializer
{
    public static async Task InitializeAsync(IServiceProvider services)
    {
        using var scope = services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<Db26TeamoneContext>();

        const string sql = @"
CREATE TABLE IF NOT EXISTS warehouse.app_user (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(100) NOT NULL UNIQUE,
    password_hash varchar(300) NOT NULL,
    password_salt varchar(300) NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS warehouse.app_order_workflow_state (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer NOT NULL UNIQUE REFERENCES warehouse.customer_order(id) ON DELETE CASCADE,
    status varchar(20) NOT NULL,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT app_order_workflow_state_status_ck CHECK (status IN ('CREATED','PICKED','PACKED','SHIPPED'))
);
";

        await db.Database.ExecuteSqlRawAsync(sql);
    }
}
